
calendar:
    event_form_type: 'RevisionTen\Calendar\Form\EventType'
    event_form_template: '@Calendar/Admin/event_form.html.twig'
    event_solr_serializer: 'RevisionTen\Calendar\Serializer\EventSerializer' # Must implement RevisionTen\Calendar\Serializer\SolrSerializerInterface
    rule_form_type: 'RevisionTen\Calendar\Form\RuleType'
    rule_form_template: '@Calendar/Admin/rule_form.html.twig'
    deviation_form_type: 'RevisionTen\Calendar\Form\DeviationType'
    deviation_form_template: '@Calendar/Admin/deviation_form.html.twig'
