services:
    RevisionTen\Calendar\Controller\AdminController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]
    RevisionTen\Calendar\Services\CalendarService:
        autowire: true
        arguments:
            $config: '%cms%'
            $calendarConfig: '%calendar%'
    RevisionTen\Calendar\EventSubscriber\EventSubscriber:
        autowire: true
        autoconfigure: true

framework:
    translator:
        paths:
            - '%kernel.project_dir%/vendor/revision-ten/calendar/Resources/translations'

cms:
    entities:
        EventRead:
            label: 'calendar.label.events'
            class: RevisionTen\Calendar\Entity\EventRead
            permissions:
                list: 'list_generic'
                search: 'search_generic'
                create: 'create_generic'
                edit: 'edit_generic'
                delete: 'delete_generic'
            templates:
                list: '@Calendar/Admin/list.html.twig'
            list:
                sort: [ 'modified', 'desc' ]
                search_fields:
                    - 'title'
                    - 'payload'
                dql_filter: 'entity.deleted IS NULL OR entity.deleted = 0'
                fields:
                    - { property: 'title', label: 'admin.label.title' }
                    - { property: 'salesStatus', label: 'calendar.label.salesStatus', template: '@Calendar/Admin/list-sales-status.html.twig' }
                    - { property: 'created', label: 'admin.label.created', type: 'datetime' }
                    - { property: 'modified', label: 'admin.label.modified', type: 'datetime' }
                actions:
                    - '-create'
                    - '-edit'
                    - '-delete'
                    - { route: 'calendar_event_edit', label: 'admin.btn.edit', icon: 'fas fa-edit', permission: 'edit_generic' }
                    - { route: 'calendar_event_delete', label: 'admin.btn.delete', icon: 'fas fa-trash', css_class: 'text-danger', permission: 'delete_generic' }
